categorical_cols = {
    'artificial_tree': None,
    'audiology': 'all',
    'balance_scale': None,
    'breast_cancer': None,
    'car': 'all',
    'chess': 'all',
    'crx': [0, 1, 3, 4, 5, 6, 8, 9, 11, 12],
    'diabetes': None,
    'ecoli_5': None,
    'flare1': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    'glass': None,
    'heart_disease': [1, 2, 5, 6, 8, 10, 11, 12],
    'heart_failure': [1, 2, 4, 7, 8],
    'hepatitis': [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    'hill_valley': None,
    'ionosphere': [0, 1],
    'iris': None,
    'lymphography': 'all',
    'mnist_test': None,
    'optdigits': None,
    'parkinsons': None,
    'seeds': None,
    'segmentation': None,
    'sonar': None,
    'tic-tac-toe': 'all',
    'titanic': [0, 1, 6],
    'treeData': None,
    'waveform': None,
    'wine': None,
    'zoo': 'all'
}
